export const quizTypes = {
  REQUEST_ALL_QUIZZES: "REQUEST_ALL_QUIZZES",
  RECEIVE_ALL_QUIZZES: "RECEIVE_ALL_QUIZZES",
  REQUEST_YOUR_QUIZZES: "REQUEST_YOUR_QUIZZES",
  RECEIVE_YOUR_QUIZZES: "RECEIVE_YOUR_QUIZZES",
  CHANGE_TITLE: "CHANGE_TITLE",
  CHANGE_DESCRIPTION: "CHANGE_DESCRIPTION",
  SUBMIT_QUIZ_START: "SUBMIT_QUIZ_START"
};
