module.exports = {
  MONGO_QUIZZES_URL: process.env.MONGO_QUIZZES_URL,
  MONGO_QUIZZES_DBNAME: process.env.MONGO_QUIZZES_DBNAME,
  MONGO_USERS_URL: process.env.MONGO_USERS_URL,
  MONGO_USERS_DBNAME: process.env.MONGO_USERS_DBNAME,
  GOOGLECLIENTID: process.env.GOOGLECLIENTID,
  GOOGLESECRET: process.env.GOOGLESECRET
}